import { StyleSheet } from 'react-native'
import { Colors, ApplicationStyles } from '../../Themes/'

export default StyleSheet.create({
    ...ApplicationStyles,
    mainContainer: {
      flex: 1,
      justifyContent: 'center',
    },
    headerContentView: {
      marginTop: 20,
      marginBottom: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerNote: {
      marginTop: 5,
      textAlign: 'center',
      fontFamily: 'OpenSans-Regular',
      fontSize: 16,
      backgroundColor: Colors.transparent,
      lineHeight: 22,
      marginHorizontal: 10,
      color: Colors.grey,
      alignSelf: 'stretch',
    },
    mainContainer2: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'center',
      flexDirection: 'column',
    },
    voucherPricePart: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 25,
      paddingVertical: 25,
    },
    euroSymbol: {
      backgroundColor: Colors.transparent,
      fontSize: 60,
      color: Colors.white,
      marginHorizontal: 4,
      fontFamily: 'Nexa Bold',
    },
    rowCenterView: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    amount1Text: {
      backgroundColor: Colors.transparent,
      fontSize: 90,
      color: Colors.white,
      marginHorizontal: 1,
      marginLeft: 5,
      fontFamily: 'Nexa Bold',
    },
    commaSymbol: {
      backgroundColor: Colors.transparent,
      fontSize: 50,
      marginBottom: 40,
      color: Colors.white,
      marginHorizontal: 1,
      marginHorizontal: 5,
      fontFamily: 'Nexa Bold',
    },
    amount2Text: {
      backgroundColor: Colors.transparent,
      fontSize: 50,
      marginBottom: 40,
      color: Colors.white,
      marginHorizontal: 1,
      fontFamily: 'Nexa Bold',
    },
    whiteBoxView: {
      flexDirection: 'column',
      paddingHorizontal: 15,
      paddingVertical: 10,
      backgroundColor: Colors.white,
      width: 300,
      borderRadius: 4,
    },
    lableStyle: {
      fontSize: 12,
      lineHeight: 16,
      color: Colors.greyDark,
      padding: 1,
    },
    issueDateText: {
      fontWeight: 'bold',
      fontSize: 14,
      lineHeight: 18,
      color: Colors.black,
      padding: 1,
    },
    issueTimeText: {
      fontWeight: 'bold',
      fontSize: 12,
      lineHeight: 16,
      color: Colors.greyDark,
      padding: 1,
    },
    nameText: {
      fontSize: 12,
      lineHeight: 16,
      color: Colors.greyDark,
      padding: 1,
    },
    centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    columnView: {
      flex: 3,
      justifyContent: 'flex-start',
      alignItems: 'center',
      flexDirection: 'column',
    },
})
